### ISSUE TITLE
konnte mit NeoQWERTZ kein ä tippen

### ISSUE THREAD

**Issue by johannesrave** [janekx21/NeoTrain#10]
heyhey, herzlichen dank für diesen top-tiptrainer!
ich hab gerade versucht den "Techno"-text mit neoqwertz zu tippen, und als dann ein 'ä' vorkam konnte ich dieses nicht eingeben.
ich bin auf Ubuntu 23.10 und nutze dort das native NeoQWERTZ layout. in anderen anwendungen klappt's mit dem 'ä'. 
danke und gruß!

**Comment by janekx21** [comment]
Danke fürs Bescheidgeben. Ich konnte es so einfach nicht reproduzieren. Kannst du mir noch sagen, welchen Browser + Version du benutzt und was https://keyjs.dev/ anzeigt, wenn du 'ä' drückst?
Gruß zurück

**Comment by johannesrave** [comment]
danke für die schnelle rückmeldung!

auf keyjs.dev liefert mir ein `ä` oben den roten text VIRTUAL KEYBOARD und folgendes log auf der console:

```
keyup { target: input#input.controls__input, key: "ä", charCode: 0, keyCode: 222 }
​
altKey: false
​bubbles: true
​cancelBubble: false
​cancelable: true
​charCode: 0
​code: "Quote"
​composed: true
​ctrlKey: false
​currentTarget: null
​defaultPrevented: false
​detail: 0
​eventPhase: 0
​explicitOriginalTarget: <input id="input" class="controls__input" placeholder="Press any key to start…" autofocus="" autocomplete="off" style="">
​isComposing: false
​isTrusted: true
​key: "ä"
​keyCode: 222
​layerX: 0
​layerY: 0
​location: 0
​metaKey: false
​originalTarget: <input id="input" class="controls__input" placeholder="Press any key to start…" autofocus="" autocomplete="off" style="">
​rangeOffset: 0
​rangeParent: null
​repeat: false
​returnValue: true
​shiftKey: false
​srcElement: <input id="input" class="controls__input" placeholder="Press any key to start…" autofocus="" autocomplete="off" style="">​
target: <input id="input" class="controls__input" placeholder="Press any key to start…" autofocus="" autocomplete="off" style="">
​timeStamp: 3859
​type: "keyup"
​view: Window https://keyjs.dev/
​which: 222
​<get isTrusted()>: function isTrusted()
​<prototype>: KeyboardEventPrototype { getModifierState: getModifierState(), initKeyboardEvent: initKeyboardEvent(), charCode: Getter, … }
```

ich hab gerade noch ö, ü und ß in entsprechenden lektionen probiert (wo sie jeweils als erste buchstaben aus dieser gruppe vorkommen) und kann die auch alle nicht tippen. ich KANN damit aber die lektionen starten, wo es heißt man müsse leertaste drücken.

| key | event-log |
| --- | --- |
| ä | keyup { target: body, key: "ö", charCode: 0, keyCode: 59 } |
| ö | keyup { target: body, key: "ä", charCode: 0, keyCode: 222 } |
| ü | keyup { target: body, key: "ü", charCode: 0, keyCode: 219 } |
| ß | keyup { target: body, key: "ß", charCode: 0, keyCode: 173 } |

**Comment by janekx21** [comment]
Ich kann das auf firefox 121.0.1 nicht reproduzieren und der wert `​key: "ä"` müsste eigentlich funktionieren. Dein ä ist das gleiche wie meins. Dein `keycode` ist ein anderer als bei mir, aber das sollte egal sein. Es könnte am "VIRTUAL KEYBOARD" liegen aber ich wüsste nicht genau warum das relevant sein sollte.

Ich denke um den  Bug zu lösen müssten wir noch mehr debuggen. Ich könnte dir einen Branch machen in dem du mal runprobieren kannst. Oder ich könnte eine Debugging-Lektion machen.

**Comment by johannesrave** [comment]
okay, danke für's nachsehen und das freundliche angebot. 
ich hab kurz in den code geschaut (ungefähr [hier](https://github.com/janekx21/NeoTrain/blob/52295740af5a11f4065d9c0ecbb8d574ad05b141/src/Pages/Typing.elm#L384)) aber aktuell zu wenig zeit um wirklich tief in die materie einzusteigen und eine elm-toolchain aufzusetzen und zu verstehen - tut mir leid.

ich bin noch auf zwei infos gestoßen, die evtl. eine rolle spielen:

- auch meine äöüß im standard QWERTZ layout werden nicht angenommen. auch in dem fall wird für diese buchstaben `VIRTUAL KEYBOARD` eingeblendet:
![image](https://github.com/janekx21/NeoTrain/assets/31467653/3e21084a-b8e4-46e0-9af7-cef1541d6ead)
- bei den buchstaben die funktionieren steht `VIRTUAL KEYBOARD` NICHT da.

ich verstehe die hintergründe davon nicht. wie erwähnt benutze ich einfach die nativ installierbaren keyboard-layouts in Ubuntu und kein virtuelles keyboard oder mobile device. vielleicht sind die layouts mithilfe von IME implementiert, falls das irgendwie sinn macht. der warnhinweis auf jskeys.dev scheint nahe zu legen dass diese tastenanschläge mit einem workaround detektiert bzw. interpretiert werden müssten oder so. vllt verhält sich die elm-standard lib da etwas anders - evtl debuggen indem man wirklich mit einem mobile-device eingaben in der app vornimmt und was rausloggt? ist nur ein schuss in's blaue, bestimmt gibt's elegantere wege. falls dir das zu stressig ist oder zu sehr cornercase, kein ding, ich wollte nur noch bescheid gegeben haben.

tut mir leid dass ich nicht weiter helfen kann. nochmal danke und gruß.

**Comment by johannesrave** [comment]
Noch ein Nachtrag: 
Ich hab es dem altehrwürdigen https://online.tipp10.com auch ausprobiert, und es bleibt weird.
Auch dort kann ich mit meinem Bluetooth-Tastatur (Logitech MX Mechanical Mini) unter Ubuntu keine Umlaute tippen - aber auf meiner Laptop-Tastatur schon und unter Windows beides 😬 Bei NeoTrain funktioniert unter Ubuntu keine der beiden Tastaturen, Windows hab ich noch nicht getestet.

Außerdem noch folgendes: Bei NeoTrain ein `ü` zu tippen wenn ein `ü` gefordert ist erzeugt auch keinen Fehler (der cursor ändert seine farbe nicht), anders als wenn ich dann eine "falsche" Taste anschlage.

Das Problem liegt also offensichtlich bei mir bzw. in meinem Ubuntu oder meinem Layout - aber ich hab keine Ahnung wie rangehen.

**Comment by johannesrave** [comment]
megageil, es funktioniert tatsächlich! herzlichen dank dass du drangeblieben bist! 
woran lag's, falls ich da mal wieder reinlaufe?

**Comment by janekx21** [comment]
Ich weiß nicht genau warum aber das "keydown" Event enthält nicht den richtigen Char. Es gibt aber zum Glück ein verstecktes Input Feld und da kommt der korrekte Char an. Web Standarts sind komisch.
