### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Jano1312** [janekx21/NeoTrain#2]
I noticed a memory leak, after about 5 to 10 dictation my system was getting nearly frozen, because all 16 GB ram and 8 GB swap were used.

Then i looked further into it:
Freshly opened the site: 41 MB
One dictation with 100 words: 2 GB
Second dictation with 100 words: 5 GB

Measured with the built in task manager in Firefox, system task manager showed similar results.

OS: Arch Linux, Kernel 6.6.2
Browser: Firefox 120.0 64 bit
Layout: Mine
Logged in, Keyboard hidden

**Comment by Jano1312** [comment]
It starts rising as soon as I start a lessons, about 100-200 MB per Minute.
No difference if typing fast or slow, as soon as the timer starts the ram usage rises.
When i press pause it slows down or even stops to rise, can't tell for sure.
When the lesson is finished or canceled it also stops to rise, but it stays on the current ram usage level.

I have tried it with Chromium, there i don't have this problem, it stays under 100 MB ram usage the whole time.

I have some browser add-ons installed in Firefox, so i tried it in a private tab, where all add-ons are disabled, but no difference.

Here is my browser info, from: [https://toolbox.googleapps.com/apps/browserinfo/](https://toolbox.googleapps.com/apps/browserinfo/)
![Screenshot_20231129_022008](https://github.com/janekx21/NeoTrain/assets/34482641/071f273c-9704-47d0-8927-dc3a09ca7c1b)

If you have some idea what else i could try to enclose the problem i will try.

As workaround i just refresh the page after every lesson right now.

Btw: I really like the app, its so simple yet so good and motivating to learn a new keyboard layout. While training I had some ideas for improvements. If you don't mind, i open some feature requests.

**Comment by janekx21** [comment]
Please feel free to submit feature requests. I will try to reproduce the issue again.

**Comment by janekx21** [comment]
Could not reproduce :< / not relevant on newer firefox versions
