### ISSUE TITLE
Feature Request: Show restart button also before lesson is started

### ISSUE THREAD

**Issue by codenius** [janekx21/NeoTrain#24]

**Comment by janekx21** [comment]
V25 Added a restart button to the typing page

**Comment by codenius** [comment]
Just noticed that too, my bad. 
However, it would still be helpful to be able to restart also before typing the first letter or maybe even show the button before starting the lesson. 
Use case: you start the lesson and the timer counts up but you get distracted somehow before you start typing. In order to not ruin your stats you wan't to restart, but currently can't in this state without typing a letter or going back to the lessons list.

**Comment by janekx21** [comment]
V25 was releleased after you issue so. Thank you for your request. I can remove the condition and show the restart button all the time.

**Comment by janekx21** [comment]
I changed the restart button to show when the lecture is unpaused :>
