### ISSUE TITLE
Registrieren nicht möglich

### ISSUE THREAD

**Issue by oehton** [janekx21/NeoTrain#25]
Hallo, 
sehr coole Lernseite für Neo und verwandte Layouts nur leider kann ich mich nicht registrieren und muss immer das Layout neu auf Bone umstellen.

Wenn ich versuche mich zu registrieren kommt immer die Meldung "Falscher Username oder falsches Password!" auch wenn ich im Registrieren Tab bin.

Dinge die ich schon probiert habe:

 - Cache und Website daten gelöscht
 - Anderen PC probiert (beides Linux)
 - Anderer Browser probiert (Firefox 126.0.1 und Google Chrome 125.0.6422.141)
 - Verschiedene Passwörter mit starken Sicherheitsanforderungen (unter IBM Valide habe ich leider keine genauen Spezifikationen gefunden)

Grüße, oehton

**Comment by janekx21** [comment]
```elm
validUsername =
                    String.all Char.isAlphaNum username
                        && (uLength >= 3)
                        && (uLength <= 32)


                validPassword =
                    -- https://www.ibm.com/docs/en/baw/19.x?topic=security-characters-that-are-valid-user-ids-passwords
                    String.all (\c -> Char.isAlphaNum c || List.member c (String.toList "!()-.?[]_`~;:@#$%^&*+= ")) password
                        && (pwLength >= 8)
                        && (pwLength <= 64)
```

Und der Benutzername darf nicht schon verwendet werden. Trifft das alles bei dir zu?

**Comment by janekx21** [comment]
Ich konnte mich gerade erfolgreich regestrieren mit username: abcdefg, pass: 1234567890

**Comment by janekx21** [comment]
Ich konnte mich gerade erfolgreich regestrieren mit username: abcdefg, pass: 1234567890

**Comment by janekx21** [comment]
Was ich auf jedenfall mal machen kann ist die Fehlernachricht etwas sinvoller zu schreiben. Mehr Detail darüber was schief gelaufen ist.

**Comment by oehton** [comment]
Ok ja mit einem anderen username funktioniert es, das wäre natüich auch mal schlau gewesen zu testen von mir. Aber vielen Dank für die schnelle Antwort und ja über eine aussagekräftigere Fehlermeldung würde ich mich auf jeden Fall freuen.
