### ISSUE TITLE
Make it mobile friendly

### ISSUE THREAD

**Issue by robertwidfen** [janekx21/NeoTrain#26]
Thanks for creating this trainer. I am using my smartphone to train Bone Layout during my vacation, but the pages do not scale properly into my screen. 
Some parts are only visible when in landscape orientation or when I switch to desktop version in browser (Chrome/Firefox).

**Comment by janekx21** [comment]
As I am on vacation myself, this has to wait until next week.

**Comment by robertwidfen** [comment]
No hurry, just wanted to let you know. ;-)

**Comment by janekx21** [comment]
It took a while and now neo train can be used on mobile. If you find any broken feature, please submit another issue. Thank you for your feedback and for using my app. Danke

**Comment by robertwidfen** [comment]
Hey thank you again, works great. 

One thing I noticedy, my Xiaomi Note 11s has a rounded display so the outer borders are cut away even when I can see them in the screenshots.  This modified screenshot shows it .... 
![Screenshot_2024-09-25-23-08-52-888_com android chrome](https://github.com/user-attachments/assets/17209ce7-ad44-4a3d-8ccb-d736f016cc00)
