### ISSUE TITLE
Can't login on second device

### ISSUE THREAD

**Issue by Jano1312** [janekx21/NeoTrain#3]
I noticed that you can't login, if you are already logged in on another device/browser.
Furthermore, there is a wrong prompt that says "Wrong username or password!" if this happens.

The only way to log in on another device is to log out on the first device.
Even disconnecting from the internet or power off the device doesn't release the account.
I'm not sure, but maybe this means, that your account could be locked forever, if the device/browser where you are logged in becomes inaccessible.

**Comment by janekx21** [comment]
I noticed the same thing the other day when I was looking through the code base. It's because the design is too clever, I'll fix it soon.

**Comment by janekx21** [comment]
Should be fixed with V19
