### ISSUE TITLE
Add Noted Layout

### ISSUE THREAD

**Issue by dariogoetz** [janekx21/NeoTrain#4]
The tool seems to support the various layouts of the Neo family. Would it be possible to add support for the newest entry in the neo family, the [Noted layout](https://www.neo-layout.org/Layouts/noted/)?

**Comment by whirgod** [comment]
I created a pr #7

**Comment by janekx21** [comment]
Thats right. The cvs file is a dictionary and way to large, also i dont know if i have the right to upload it here. Maybe i can link it somewhere. Sorry for the confusion.
The other part of adding a layout is extending the `Layout` type inside `Types.elm`. The resulting compiler errors should lead you to the relevant code parts. Was that helpfull?

**Comment by whirgod** [comment]
Thanks for the pointers. I added it and published the PR in case you want to merge it like this and just run the convert script yourself.

**Comment by janekx21** [comment]
The 'j' char was missing from the Noted layout in the `convert.py`. I fixed this and deployed. Nicely done ^^ Thank you
