### ISSUE TITLE
Anmeldungsfehler

### ISSUE THREAD

**Issue by FabulousOne** [janekx21/NeoTrain#5]
Hi @janekx21 
vielen Dank für diesen Tipptrainer. 
Allerdings habe ich immer Probleme beim Anmelden. Er sagt immer `Falscher Username oder falsches Password!`. Dann registriere ich mich neu, und beim nächsten Mal kennt er mich nicht mehr ... Das ist schade, weil mein Fortschritt nicht abgespeichert wird. 
Gibt es dafür eine Lösung?
Vielen Dank!

**Comment by janekx21** [comment]
Danke für dein Feedback! Das Problem stammt aus der Benutzer verwaltung. Bis lang war es nicht möglich sich auf zwei Geräten gleichzeitig anzumelden. Der neue Release löst das Problem. Falls du weitere Verbesserungsvorschläge hast, schreib mir gerne ein Issue.
