### ISSUE TITLE
Enter on layer 4 does not work

### ISSUE THREAD

**Issue by Jano1312** [janekx21/NeoTrain#8]
I was doing a lesson with enter/line-break for the first time today and noticed, that enter on layer 4 does not work for me, only the dedicated one.

I am using the linux xkb mine layout.

**Comment by janekx21** [comment]
Can you be more specific?
- is the preview broken?
- is the dictation not advancing?
- what about that key outside of neo-train like a text editor?
- what does https://keyjs.dev/ show when hitting it?

**Comment by Jano1312** [comment]
Nothing happens, like the wrong key is pressed.
Outside it works everywhere I tested it: text editor, browser, terminal,...

This is normal enter:
![image](https://github.com/janekx21/NeoTrain/assets/34482641/c9db96fc-0d95-42e9-9727-e275f51da166)

This on layer 4:
![image](https://github.com/janekx21/NeoTrain/assets/34482641/7facdddf-278f-4e55-bda4-563d4ef5a251)

**Comment by janekx21** [comment]
Fixed with V21
